sudo: false

language: node_js

dist: trusty

node_js:
  - "10.14.2"
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install --frozen-lockfile

addons:
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /
  chrome: stable

services:
  - docker

script:
  - npm test
  - ./artifact.sh

matrix:
  allow_failures:
    - node_js: node
